# Generated by Django 4.0.5 on 2022-06-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='time_length',
            field=models.TimeField(),
        ),
    ]
