# Generated by Django 4.0.5 on 2022-06-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('author', models.CharField(db_index=True, max_length=30)),
                ('time_length', models.DurationField()),
                ('upload_date', models.DateField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
